# path: /home/jadelaossa/Workspaces/CIDaeN/tfm/automatic-receipts-recognition/data  # local env
# path: /content/drive/MyDrive/automatic-receipts-recognition/data # google colab real data
path: /content/drive/MyDrive/automatic-receipts-recognition/data/digital/mercadona # google colab digital data
train: train/images  # train images (relative to 'path') 4 images
val: valid/images  # val images (relative to 'path') 4 images
test:  test/images # test images (optional)

# Classes for real data
# names:
  # 0: item
  # 1: store_name
  # 2: total_amount
  # 3: transaction_date

# Classes for digital data
names: 
  0: item_description
  1: store_address
  2: store_name
  3: total_amount
  4: transaction_datetime

# Download script/URL (optional)
download: